wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716534132.0
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 49
      - 51
      - 53
      - 55
      - 103
      3:
      - 7
      - 19
      - 23
      4: 3.10.13
      5: 0.16.4
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train/loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
model_name:
  desc: null
  value: camembert-base
num_labels:
  desc: null
  value: 3
lr:
  desc: null
  value: 5.0e-06
weight_decay:
  desc: null
  value: 0
typ:
  desc: null
  value: arg
from_scratch:
  desc: null
  value: false
wd:
  desc: null
  value: 0
